---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAm9hzffibkQdoNM1Fx25aOsdrc3c6CrXcemeo486GakQ/hsK3idq2fuMJJ3iR1YucCvq+AyWJpLHiIK6Oec6pWc5B999bYO/7O1IgNLQdEBDWr6d2RBpjBkd0Wr2EbIKvL7ig9O6oaNtzsd5iJ4Mu/gOLnhVsf206DKU15Kk7/forX/05djqt00V3MRz6S9z8gn4HttckOnPKT9gv5jwNvUGYQy/nRfn61eK86o7t9/I/8UxbJb8FBC5CfF+FKuuR+2ERBnvzGZ0hEFfKeXAKROVx1jCLFtHtu/glvYJ5uuv4CmDd5FYSGbnHPCbrC0Ev//DF174ToQ/Z4A3OjoYKTlREqqAqve+RAnKsZBZI/voXqog+iippjP8DjhATl/x5HlZ7R2pLT/OODMNq7oSc0uUeTbpZrjMeaNlHduoo526lSNY2k1eSTVys8UDwsiRN6YCgAvBzOIoNfolFfpHOHuRP/4fV+sTEDBakpViDPwWtpK8LArUb/1AMT+PucdbkipWGj2bdZftrF7TPHmtwApf+GxUyxc9ZYK6rAh0SuHqVAnW1nMJBMYTFH+mtgoKny1jKxuaiJfVOqVZiy9xvRtp8WEWHsXVnoOUfNyvsWK6gaiU6cXDJZyB4ZZtIpOUTV2/lM51aGsRwbIjrW+zR23fPUXkmWt/vAT4xd6WhmBNQh0ugycobAq7s+ikb/0wmJ7ZyQ9BYN1C4kMPqlVrub8hx4BNmFKd0=
    admin-user: AgB0OEInXcjmM36eXKsX1+18wMZBLr8g8abw/j74s4yJIipYKWSRtrp2ibbqsWKoO7mlrzQuAivxxmkk43wiWGMNLHYKyVd7KubFb6kmyhQ3IGgS8lsiJDNVrW+pNPfafd7vXt5HiZasGTWLMGeefGFcT0WUL2BrbmFukhPwPifTjUcPO8LDXBrItU+73PyhMOd4KB6dNVFm5lC9SsDv1Gdkwf21n7Vz+JZNfYAVnUzijZIjYj5LAEY5fjoEfwxdKBe9khDH8YaCSRJO7Vp0d6RxBKWMo+h3iZeMGj0fPA2kRd12oKByurLsEjaQ9xWC7Z8JwAyfpfSYE2MLY+9WE/h99s/ub8VhU3wFXbfjVKWgI/qhYYzJfClAAZbk2DIpHJVhtQKFiFKDWxeB3W9hZBbDK9+QiEr9rbOL6JpDYFZcMWxnBkQ9XzMs0OvpQB/aseWbhXzqnQIKk/DODPH0iv4I8pdOq0pPMzRy9iGd57xaAm8F5O2qb9eD2SSbC1z4OJKS67532GXW7T4X5bZ8YCh6Ny+AWFbaFdLW2RIe6pKbYvXKD937n2AcqNZbNC/QMbmnElLOgfwwS75cjiryhDdm/PpgOUTH7gGugjpnJK73yjKIdSLxJxpN+Ovm4cK5Vjk9a+aLhHbi46B+Gy7EOwIRmtpb9ONYqf/85t/wZ+yqbFAGV4lK718RkFYotldXz59ye0XTjA==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
